$eclmaps = @{
    "08"      = "$PSScriptRoot/eclmap/th08.eclm"
    "10"      = "$PSScriptRoot/eclmap/th11.eclm"
    "11"      = "$PSScriptRoot/eclmap/th11.eclm"
    "12"      = "$PSScriptRoot/eclmap/th12.eclm"
    "128"     = "$PSScriptRoot/eclmap/th12.eclm"
    "13"      = "$PSScriptRoot/eclmap/th13.eclm"
    "14"      = "$PSScriptRoot/eclmap/th14.eclm"
    "143"     = "$PSScriptRoot/eclmap/th14.eclm"
    "15"      = "$PSScriptRoot/eclmap/th15.eclm"
    "16"      = "$PSScriptRoot/eclmap/th16.eclm"
    "165"     = "$PSScriptRoot/eclmap/th16.eclm"
    "17"      = "$PSScriptRoot/eclmap/th17.eclm"
    "alcostg" = "$PSScriptRoot/eclmap/th11.eclm"
}

$anmmaps = @{
    "06"  = "$PSScriptRoot/anmmap/v0.anmm"
    "07"  = "$PSScriptRoot/anmmap/v2.anmm"
    "08"  = "$PSScriptRoot/anmmap/v2.anmm"
    "09"  = "$PSScriptRoot/anmmap/v2.anmm"
    "095" = "$PSScriptRoot/anmmap/v4.anmm"
    "10"  = "$PSScriptRoot/anmmap/v4.anmm"
    "11"  = "$PSScriptRoot/anmmap/v4.anmm"
    "12"  = "$PSScriptRoot/anmmap/v4.anmm"
    "128" = "$PSScriptRoot/anmmap/v4.anmm"
    "13"  = "$PSScriptRoot/anmmap/v8.anmm"
    "14"  = "$PSScriptRoot/anmmap/v8.anmm"
    "143" = "$PSScriptRoot/anmmap/v8.anmm"
    "15"  = "$PSScriptRoot/anmmap/v8.anmm"
    "16"  = "$PSScriptRoot/anmmap/v8.anmm"
    "165" = "$PSScriptRoot/anmmap/v8.anmm"
    "17"  = "$PSScriptRoot/anmmap/v8.anmm"
}